### ISSUE TITLE
Noticed this is a thing....

### ISSUE THREAD

**Issue by Turbski** [AidFTech/MKA-Lite#2]
I have a 07 335i e90 with IDrive, I noticed your in austin which isn't far from me. I wanted to see if its possible if I can help bug test and what not. Telegram: @turbski
If you have any other form of contact, let me know thanks.

**Comment by tedsalmon** [comment]
MOST isn’t in the works right now, but it’s not outside the question. I am admittedly an E46 guy, so I’m less familiar with the E65 based cars. @AidFTech is a Honda boi, FWIW.

**Comment by Turbski** [comment]
I see okay, well good luck
